version: '3.8'
services:
  redis:
    image: redislabs/redismod:latest
    ports:
      - '6379:6379'
    networks:
      - app
    volumes:
      - redis_data:/data

  mysql:
    image: mysql:latest
    ports:
      - '3307:3306'
    env_file: ./.env
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - app
    volumes:
      - mysql_data:/var/lib/mysql

  nodejs_training:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - mysql
    networks:
      - app

volumes:
  redis_data:
  mysql_data:

networks:
  app:
    driver: bridge
